# Generated by Django 4.0.6 on 2022-08-02 00:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('apellido', models.CharField(max_length=64)),
                ('fechaNacimiento', models.DateField(blank=True, null=True)),
                ('fechaFallecimiento', models.DateField(blank=True, null=True, verbose_name='Died')),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=64)),
                ('descripcion', models.TextField(help_text='Sinopsis de la palicula', max_length=200)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('duracion', models.DateField(blank=True, null=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='peliculas.autor')),
                ('genero', models.ManyToManyField(to='peliculas.genero')),
            ],
        ),
        migrations.CreateModel(
            name='PeliculaInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID unico de pelicula', primary_key=True, serialize=False)),
                ('pelicula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='peliculas.pelicula')),
            ],
        ),
    ]
