# Generated by Django 4.0.6 on 2022-08-02 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_autor_pelicula_peliculainstance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Autor',
            new_name='Director',
        ),
    ]
