# Generated by Django 4.0.6 on 2022-08-02 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0003_rename_autor_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
    ]
