# Generated by Django 4.0.6 on 2022-08-02 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0004_pelicula_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='duracion',
            field=models.CharField(blank=True, help_text='formato: hh:mm 01:58', max_length=5, null=True),
        ),
    ]
